<%@ page import="tidemedia.cms.util.Util,tidemedia.cms.system.*"%><%@ page contentType="text/html;charset=utf-8" %><%response.setContentType("text/xml");%><%response.setHeader("Pragma","No-cache"); response.setHeader("Cache-Control","no-cache"); response.setDateHeader("Expires", 0);%><?xml version="1.0"  encoding="utf-8"?>
<%@ include file="../config1.jsp"%><tree><tree text="珠海台" src="../channel/channel_xml.jsp?id=7714" action="javascript:show(7714);&quot; ChannelID=7714 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="CUTV" src="../channel/channel_xml.jsp?id=7705" action="javascript:show(7705);&quot; ChannelID=7705 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="深圳台" src="../channel/channel_xml.jsp?id=7706" action="javascript:show(7706);&quot; ChannelID=7706 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="柳州台" src="../channel/channel_xml.jsp?id=7707" action="javascript:show(7707);&quot; ChannelID=7707 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="宁波台" src="../channel/channel_xml.jsp?id=7708" action="javascript:show(7708);&quot; ChannelID=7708 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="郑州台" src="../channel/channel_xml.jsp?id=7709" action="javascript:show(7709);&quot; ChannelID=7709 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="大连台" src="../channel/channel_xml.jsp?id=7710" action="javascript:show(7710);&quot; ChannelID=7710 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="南通台" src="../channel/channel_xml.jsp?id=7711" action="javascript:show(7711);&quot; ChannelID=7711 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="苏州台" src="../channel/channel_xml.jsp?id=7712" action="javascript:show(7712);&quot; ChannelID=7712 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="青岛台" src="../channel/channel_xml.jsp?id=7713" action="javascript:show(7713);&quot; ChannelID=7713 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="石家庄台" action="javascript:show(7716);&quot; ChannelID=7716 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="西安台" src="../channel/channel_xml.jsp?id=7717" action="javascript:show(7717);&quot; ChannelID=7717 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="南宁台" src="../channel/channel_xml.jsp?id=7718" action="javascript:show(7718);&quot; ChannelID=7718 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="绍兴台" src="../channel/channel_xml.jsp?id=7719" action="javascript:show(7719);&quot; ChannelID=7719 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="安阳台" src="../channel/channel_xml.jsp?id=7720" action="javascript:show(7720);&quot; ChannelID=7720 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="台州台" src="../channel/channel_xml.jsp?id=7721" action="javascript:show(7721);&quot; ChannelID=7721 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="昆明台" action="javascript:show(7722);&quot; ChannelID=7722 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="时尚网" action="javascript:show(7723);&quot; ChannelID=7723 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="烟台日报" action="javascript:show(7724);&quot; ChannelID=7724 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="亚心网" action="javascript:show(7725);&quot; ChannelID=7725 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="新闻晚报" action="javascript:show(7726);&quot; ChannelID=7726 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="黑龙江报业" action="javascript:show(7727);&quot; ChannelID=7727 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="吉林台" action="javascript:show(7728);&quot; ChannelID=7728 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="济南台" src="../channel/channel_xml.jsp?id=7729" action="javascript:show(7729);&quot; ChannelID=7729 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="西宁台" src="../channel/channel_xml.jsp?id=7730" action="javascript:show(7730);&quot; ChannelID=7730 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="武汉台" src="../channel/channel_xml.jsp?id=7731" action="javascript:show(7731);&quot; ChannelID=7731 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="泰州台" src="../channel/channel_xml.jsp?id=7732" action="javascript:show(7732);&quot; ChannelID=7732 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
<tree text="兰州台" src="../channel/channel_xml.jsp?id=7733" action="javascript:show(7733);&quot; ChannelID=7733 ChannelType=&quot;1" icon="../images/tree/16_channel_class_icon.png" openIcon="../images/tree/16_openchannel_class_icon.png" />
</tree>
