server:
  port: 888
spring:
  application:
    name: tcenter
  freemarker:
    settings:
      number_format: 0 # 用freemarker 输出数字时，默认会每三位有逗号问题
    allowRequestOverride: false
    allowSessionOverride: false
    cache: false
    checkTemplateLocation: true
    contentType: text/html
    exposeRequestAttributes: false
    exposeSessionAttributes: true
    exposeSpringMacroHelpers: false
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下
    spring.freemarker.settings:
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
    request-context-attribute: request
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: tidemedia.tcenter.entity