<%@ page contentType="text/html;charset=utf-8" %><%response.setContentType("text/xml");%><%String root = (request.getRequestURL()+"").replace("/google_button.jsp","/");%><?xml version="1.0" encoding="utf-8"?>
<custombuttons xmlns="http://toolbar.google.com/custombuttons/">

  <button>
<title>TideCMS</title>
<site><%=root%>page.jsp?Url={url}</site>
 <icon mode="base64" type="image/x-icon">
AAABAAIAEBAAAAEACABoBQAAJgAAABAQAAABACAAaAQAAI4FAAAoAAAAEAAAACAAAAABAAgAAAAA
AAABAAAAAAAAAAAAAAABAAAAAQAAAAAAAMV4AwDmfQAADIBGABmdWwAlqWcAUb5mACLHZwAixmgA
JctoACLKbwAjzHMA64YOAPePAAD/kgAA/pUAAP+0AAArAKgAKwCxACwAywArANYAOADuAC0A9AAw
APEANgD0ADsA9QA3APkAOQD6AFIo/wAAd+UASO+PAACi5QAAp+UAA73rAArS+QAK0/0ADtT9ABDU
/QA05f8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA////AAAABAQEBAAAAAAMDAwMAAAABB4eHh4EAAAMEBAQEAwABB4eAwMF
BQMBDg4BARAQDAQeAwAAAwMBDg4BAAABEAwECAMAAAABDg8BAAAAARAMBAgIAwACDg8BHR0AAQ0O
DAAEBwoDAQIBHSAgHQECAQAAAAMKCgMBAAAdICAdAQAAAAARAwYGAwAAER0gIR0AAAARFBIDBAQD
ERMRHSEkIAARFhcRAAMDERcVEQAgJSQhFBcRAAAAERsZEQAAACAkIRQcEQAAERoXESAgAAAfJiEU
HBwRERcXESAiJSAfJiYhABQcHBwcFAAAISYmJiYhAAAAFBQUFAAAAAAhISEhAADDwwAAgYEAAAAA
AAAYGAAAHDgAAAgQAACAAQAAwYMAAMGDAACAAQAACBAAABw4AAAYGAAAAAAAAIGBAADDwwAAKAAA
ABAAAAAgAAAAAQAgAAAAAABABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZ1b/xmdW/8ZnVv/
GZ1b/wAAAAAAAAAAAAAAAAAAAADrhg7/64YO/+uGDv/rhg7/AAAAAAAAAAAAAAAAGZ1b/0jvj/9I
74//SO+P/0jvj/8ZnVv/AAAAAAAAAADrhg7//7QA//+0AP//tAD//7QA/+uGDv8AAAAAGZ1b/0jv
j/9I74//DIBG/wyARv8lqWf/Jaln/wyARv/FeAP//5MA//+TAP/FeAP/xXgD//+0AP//tAD/64YO
/xmdW/9I74//DIBG/wAAAAAAAAAADIBG/wyARv/FeAP//pUA//+VAP/FeAP/AAAAAAAAAADFeAP/
/7QA/+uGDv8ZnVv/IsZo/wyARv8AAAAAAAAAAAAAAADFeAP//5MA//+WAP/FeAP/AAAAAAAAAAAA
AAAAxXgD//+0AP/rhg7/GZ1b/yLGaP8ixmj/DIBG/wAAAADmfQD//5QA//+VAP/FeAP/AHfl/wB3
5f8AAAAAxXgD//ePAP//kQD/64YO/wAAAAAZnVv/Isdn/yLKb/8MgEb/xXgD/+Z9AP/FeAP/AHfl
/wCn5f8Ap+X/AHfl/8V4A//mfQD/xXgD/wAAAAAAAAAAAAAAAAyARv8ly2j/I8xz/wyARv/FeAP/
AAAAAAAAAAAAd+X/AKfl/wCn5f8Ad+X/xXgD/wAAAAAAAAAAAAAAAAAAAAArAKj/DIBG/1G+Zv9R
vmb/DIBG/wAAAAAAAAAAKwCo/wB35f8Ap+X/A73r/wB35f8AAAAAAAAAAAAAAAArAKj/KwDW/ysA
sf8MgEb/GZ1b/xmdW/8MgEb/KwCo/ywAy/8rAKj/AHfl/wO96/8N1P7/AKLl/wAAAAArAKj/LQD0
/zEA8P8rAKj/AAAAAAyARv8MgEb/KwCo/zEA8P84AO7/KwCo/wAAAAAAouX/ENT9/wrT/f8Dvev/
KwDW/zAA8/8rAKj/AAAAAAAAAAAAAAAAKwCo/zkA+v87APX/KwCo/wAAAAAAAAAAAAAAAACi5f8P
1P3/A73r/ysA1v9SKP//KwCo/wAAAAAAAAAAKwCo/zcA+f82APT/KwCo/wCi5f8AouX/AAAAAAAA
AAAAouX/NOX//wO96/8rANb/Uij//1Io//8rAKj/KwCo/zIA8/8wAPP/KwCo/wCi5f8K0vn/ENT9
/wCi5f8AouX/NOX//zTl//8Dvev/AAAAACsA1v9SKP//Uij//1Io//9SKP//KwDW/wAAAAAAAAAA
A73r/zTl//805f//NOX//zTl//8Dvev/AAAAAAAAAAAAAAAAKwDW/ysA1v8rANb/KwDW/wAAAAAA
AAAAAAAAAAAAAAADvev/A73r/wO96/8Dvev/AAAAAAAAAADDwwAAgYEAAAAAAAAYGAAAHDgAAAgQ
AACAAQAAwYMAAMGDAACAAQAACBAAABw4AAAYGAAAAAAAAIGBAADDwwAA
    </icon>

  </button>
</custombuttons>